import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>MAIN APP HEADER</header>
        {children}
        <footer>MAIN APP FOOTER</footer>
      </body>
    </html>
  )
}
